# This workflow marks issues and pull requests as stale if they haven't had any activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale

name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '35 5 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
